import { createClient } from "https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.111.0/+esm";
const sb=createClient("https://kmhadzujovvxvpgblgkk.supabase.co","sb_publishable_JDcJGMDybnrOZcSRqtpzDg_6Ul0jr2Y",{auth:{persistSession:true,autoRefreshToken:true}});
const GAME_LABELS={"bl01":"Bundesliga · 1. Spieltag · VfB Stuttgart","bl02":"Bundesliga · 2. Spieltag · FC Schalke 04","bl03":"Bundesliga · 3. Spieltag · SV 07 Elversberg","bl04":"Bundesliga · 4. Spieltag · 1. FC Union Berlin","bl05":"Bundesliga · 5. Spieltag · FC Augsburg","bl06":"Bundesliga · 6. Spieltag · RB Leipzig","bl07":"Bundesliga · 7. Spieltag · SC Freiburg","bl08":"Bundesliga · 8. Spieltag · Borussia Dortmund","bl09":"Bundesliga · 9. Spieltag · 1. FSV Mainz 05","bl10":"Bundesliga · 10. Spieltag · 1. FC Köln","bl11":"Bundesliga · 11. Spieltag · Hamburger SV","bl12":"Bundesliga · 12. Spieltag · SC Paderborn 07","bl13":"Bundesliga · 13. Spieltag · TSG Hoffenheim","bl14":"Bundesliga · 14. Spieltag · SV Werder Bremen","bl15":"Bundesliga · 15. Spieltag · Borussia Mönchengladbach","bl16":"Bundesliga · 16. Spieltag · Bayer 04 Leverkusen","bl17":"Bundesliga · 17. Spieltag · Eintracht Frankfurt","bl18":"Bundesliga · 18. Spieltag · VfB Stuttgart","bl19":"Bundesliga · 19. Spieltag · FC Schalke 04","bl20":"Bundesliga · 20. Spieltag · SV 07 Elversberg","bl21":"Bundesliga · 21. Spieltag · 1. FC Union Berlin","bl22":"Bundesliga · 22. Spieltag · FC Augsburg","bl23":"Bundesliga · 23. Spieltag · RB Leipzig","bl24":"Bundesliga · 24. Spieltag · SC Freiburg","bl25":"Bundesliga · 25. Spieltag · Borussia Dortmund","bl26":"Bundesliga · 26. Spieltag · 1. FSV Mainz 05","bl27":"Bundesliga · 27. Spieltag · 1. FC Köln","bl28":"Bundesliga · 28. Spieltag · Hamburger SV","bl29":"Bundesliga · 29. Spieltag · SC Paderborn 07","bl30":"Bundesliga · 30. Spieltag · TSG Hoffenheim","bl31":"Bundesliga · 31. Spieltag · SV Werder Bremen","bl32":"Bundesliga · 32. Spieltag · Borussia Mönchengladbach","bl33":"Bundesliga · 33. Spieltag · Bayer 04 Leverkusen","bl34":"Bundesliga · 34. Spieltag · Eintracht Frankfurt","dfb01":"DFB-Pokal · 1. Runde · VfL Osnabrück","dfb02":"DFB-Pokal · 2. Runde","dfb03":"DFB-Pokal · Achtelfinale","dfb04a":"DFB-Pokal · Viertelfinale","dfb04b":"DFB-Pokal · Viertelfinale – alternatives Fenster","dfb05":"DFB-Pokal · Halbfinale","dfb06":"DFB-Pokal · Finale","cl01":"Champions League · Ligaphase 1","cl02":"Champions League · Ligaphase 2","cl03":"Champions League · Ligaphase 3","cl04":"Champions League · Ligaphase 4","cl05":"Champions League · Ligaphase 5","cl06":"Champions League · Ligaphase 6","cl07":"Champions League · Ligaphase 7","cl08":"Champions League · Ligaphase 8","clpo1":"Champions League · Play-off Hinspiel","clpo2":"Champions League · Play-off Rückspiel","clr161":"Champions League · Achtelfinale Hinspiel","clr162":"Champions League · Achtelfinale Rückspiel","clqf1":"Champions League · Viertelfinale Hinspiel","clqf2":"Champions League · Viertelfinale Rückspiel","clsf1":"Champions League · Halbfinale Hinspiel","clsf2":"Champions League · Halbfinale Rückspiel","clfinal":"Champions League · Finale"};
const PERSON={p1:"Patrick",p2:"Reini",g1:"Gast 1",g2:"Gast 2"};
const content=document.getElementById("content"),userFilter=document.getElementById("userFilter"),typeFilter=document.getElementById("typeFilter"),search=document.getElementById("search");
let LOGS=[];
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function same(a,b){return JSON.stringify(a??null)===JSON.stringify(b??null)}
function fmtDate(ts){return new Intl.DateTimeFormat("de-DE",{dateStyle:"medium",timeStyle:"short",timeZone:"Europe/Berlin"}).format(new Date(ts))}
function gameName(id){return GAME_LABELS[id]||id||"Saisonübersicht"}
function names(arr,g){return (arr||[]).map(v=>v==="g1"||v==="g2"?(g?.[v]||PERSON[v]):PERSON[v]||v).join(", ")||"Offen"}
function stateChanges(log){const a=log.before_data||{},b=log.after_data||{},out=[];const ids=new Set([...Object.keys(a.assignments||{}),...Object.keys(b.assignments||{}),...Object.keys(a.guests||{}),...Object.keys(b.guests||{}),...Object.keys(a.paid||{}),...Object.keys(b.paid||{}),...Object.keys(a.notes||{}),...Object.keys(b.notes||{})]);for(const id of ids){const aa=(a.assignments||{})[id]||[],ba=(b.assignments||{})[id]||[];const ag=(a.guests||{})[id]||{},bg=(b.guests||{})[id]||{};if(!same(aa,ba))out.push({id,text:`Belegung: ${names(aa,ag)} → ${names(ba,bg)}`});for(const g of ["g1","g2"])if((ag[g]||"")!==(bg[g]||""))out.push({id,text:`${PERSON[g]}: "${ag[g]||"–"}" → "${bg[g]||"–"}"`});const ap=(a.paid||{})[id]||{},bp=(b.paid||{})[id]||{};for(const p of ["p1","p2","g1","g2"])if(!!ap[p]!==!!bp[p])out.push({id,text:`${PERSON[p]}: ${bp[p]?"bezahlt":"nicht bezahlt"}`});if(((a.notes||{})[id]||"")!==((b.notes||{})[id]||""))out.push({id,text:"Notiz geändert"});}return out.length?out:[{id:null,text:"Saisonübersicht geändert"}];}
function fixtureChanges(log){const a=log.before_data||{},b=log.after_data||{},out=[],id=log.entity_id;const fields=[["opponent","Gegner"],["start_date","Datum"],["end_date","Datumsende"],["kickoff_time","Anstoß"],["home","Heim/Auswärts"],["active","Aktiv"]];for(const [k,label] of fields){if(!same(a[k],b[k])){let av=a[k]??"–",bv=b[k]??"–";if(k==="home"){av=a[k]===true?"Heim":a[k]===false?"Auswärts":"–";bv=b[k]===true?"Heim":b[k]===false?"Auswärts":"–"}if(k==="active"){av=a[k]===false?"Nein":"Ja";bv=b[k]===false?"Nein":"Ja"}out.push({id,text:`${label}: ${av} → ${bv}`});}}return out.length?out:[{id,text:"Offizielle Termindaten aktualisiert"}];}
function syncChanges(log){const b=log.after_data||{};const status=b.status==="success"?"erfolgreich":b.status==="failed"?"fehlgeschlagen":(b.status||"ausgeführt");const out=[{id:null,text:`Spieltagssync ${status}`}];if(Number.isFinite(Number(b.found_count)))out.push({id:null,text:`Gefundene Spiele: ${b.found_count}`});if(Number.isFinite(Number(b.updated_count)))out.push({id:null,text:`Aktualisierte Einträge: ${b.updated_count}`});if(b.message)out.push({id:null,text:String(b.message)});return out;}
function changesFor(log){if(log.entity_type==="fixture")return fixtureChanges(log);if(log.entity_type==="sync_run")return syncChanges(log);return stateChanges(log)}
function typeLabel(log){if(log.entity_type==="fixture")return "Termin-Sync";if(log.entity_type==="sync_run")return "Spieltagssync";return "Änderung"}
function render(){const uf=userFilter.value,tf=typeFilter.value,q=search.value.trim().toLowerCase();const rows=LOGS.filter(log=>{if(uf&&log.actor_name!==uf)return false;if(tf&&log.entity_type!==tf)return false;const changes=changesFor(log);const hay=[log.actor_name,gameName(log.entity_id),...changes.map(x=>x.text)].join(" ").toLowerCase();return !q||hay.includes(q);});if(!rows.length){content.className="empty";content.textContent="Noch keine History-Einträge vorhanden.";return}content.className="log";content.innerHTML=rows.map(log=>{const changes=changesFor(log);const ids=[...new Set(changes.map(x=>x.id).filter(Boolean))];const games=log.entity_type==="sync_run"?"Spieltagssynchronisierung":(ids.length?ids.map(gameName).join(" · "):gameName(log.entity_id));const system=log.actor_name==="System";return `<article class="entry"><div class="row"><div><div class="who">Ausgeführt von ${esc(log.actor_name||"Benutzer")}</div><div class="time">${fmtDate(log.created_at)}</div></div><span class="badge ${system?"system":""}">${typeLabel(log)}</span></div><div class="game">${esc(games)}</div><ul class="changes">${changes.map(c=>`<li>${esc(c.text)}</li>`).join("")}</ul></article>`;}).join("");}
async function boot(){const {data:{session}}=await sb.auth.getSession();if(!session){location.replace("index.html");return}const {data,error}=await sb.from("history_log").select("id,created_at,actor_name,entity_type,entity_id,before_data,after_data").order("created_at",{ascending:false}).limit(1000);if(error){content.className="empty";content.textContent="History konnte nicht geladen werden. Bitte History-Migration in Supabase ausführen.";console.error(error);return}LOGS=data||[];[...new Set(LOGS.map(x=>x.actor_name).filter(Boolean))].sort().forEach(n=>userFilter.insertAdjacentHTML("beforeend",`<option value="${esc(n)}">${esc(n)}</option>`));userFilter.onchange=typeFilter.onchange=search.oninput=render;render();}
boot();
