import { BASE_M } from './schedule.js';
import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.111.0/+esm';
const sb=createClient('https://kmhadzujovvxvpgblgkk.supabase.co','sb_publishable_JDcJGMDybnrOZcSRqtpzDg_6Ul0jr2Y',{auth:{persistSession:true,autoRefreshToken:true}});
const $=id=>document.getElementById(id);const sel=$('historyGroup'),type=$('historyType'),search=$('historySearch'),content=$('historyContent');
let user=null,profile=null,groups=[],current=null,logs=[],tickets=new Map(),fixtures=new Map(BASE_M.map(m=>[m.id,m]));
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function money(v){return new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR'}).format(Number(v)||0)}
function fmt(ts){return new Intl.DateTimeFormat('de-DE',{dateStyle:'medium',timeStyle:'short',timeZone:'Europe/Berlin'}).format(new Date(ts))}
function fixtureName(id){const m=fixtures.get(id);return m?`${m.l} · ${m.o}`:id||'Saison'}
function ticketName(id,before={},after={}){return tickets.get(id)?.label||after.label||before.label||'Dauerkarte'}
function actionLabel(log){if(log.entity_type==='allocations')return'Belegung';if(log.entity_type==='fixture_notes')return'Notiz';if(log.entity_type==='tickets')return'Dauerkarte';if(log.entity_type==='paypal')return'PayPal';if(log.entity_type==='invite')return'Einladung';if(log.entity_type==='membership_request')return'Bewerbung';return log.entity_type}
function roleText(v){return v==='admin'?'Admin':'Gast'}
function summary(log){const a=log.before_data||{},b=log.after_data||{};
 if(log.entity_type==='paypal'){const d=b;const act=log.action==='share_opened'?'Zahlungsaufforderung geteilt':'PayPal-Nachricht kopiert';return{title:act,sub:[d.person,d.ticket,d.match_label,d.amount!=null?money(d.amount):''].filter(Boolean).join(' · ')}}
 if(log.entity_type==='invite'){return{title:'Neue Einladung erstellt',sub:b.expires_at?`Gültig bis ${fmt(b.expires_at)}`:'Einladungslink erzeugt'}}
 if(log.entity_type==='membership_request'){
   if(log.action==='join_requested')return{title:'Neue Beitrittsanfrage',sub:b.username?`@${b.username}`:'Freigabe ausstehend'};
   if(log.action==='join_approved')return{title:`${b.name||'Bewerber'} freigegeben`,sub:`Rolle: ${roleText(b.role)}`};
   if(log.action==='join_rejected')return{title:`${b.name||'Bewerber'} abgelehnt`,sub:'Beitrittsanfrage wurde abgelehnt'};
 }
 if(log.entity_type==='allocations'){
   const fixture=b.fixture_id||a.fixture_id||String(log.entity_id||'').split(':')[0],ticket=b.ticket_id||a.ticket_id||String(log.entity_id||'').split(':')[1],name=ticketName(ticket,a,b);
   if(log.action==='created')return{title:`${name} vergeben`,sub:`${b.attendee_name||'Name offen'} · ${fixtureName(fixture)}`};
   if(log.action==='deleted')return{title:`${name} freigegeben`,sub:`${a.attendee_name||'–'} · ${fixtureName(fixture)}`};
   const changes=[];if((a.attendee_name||'')!==(b.attendee_name||''))changes.push(`Name: ${a.attendee_name||'–'} → ${b.attendee_name||'–'}`);if(!!a.paid!==!!b.paid)changes.push(b.paid?'als bezahlt markiert':'Zahlung wieder offen');if(Number(a.amount)!==Number(b.amount))changes.push(`Betrag: ${money(a.amount)} → ${money(b.amount)}`);return{title:`${name} aktualisiert`,sub:`${fixtureName(fixture)}${changes.length?' · '+changes.join(' · '):''}`};
 }
 if(log.entity_type==='fixture_notes'){const fixture=b.fixture_id||a.fixture_id||log.entity_id;if(log.action==='deleted')return{title:'Notiz entfernt',sub:fixtureName(fixture)};return{title:log.action==='created'?'Notiz hinzugefügt':'Notiz geändert',sub:`${fixtureName(fixture)} · ${(b.note||'').slice(0,120)}`}}
 if(log.entity_type==='tickets'){const name=ticketName(b.id||a.id,a,b);return{title:log.action==='created'?`${name} hinzugefügt`:log.action==='deleted'?`${name} gelöscht`:`${name} geändert`,sub:[b.block&&`Block ${b.block}`,b.row_label&&`Reihe ${b.row_label}`,b.seat&&`Sitz ${b.seat}`].filter(Boolean).join(' · ')}}
 return{title:log.action||'Änderung',sub:fixtureName(log.entity_id)};
}
function render(){const t=type.value,q=search.value.trim().toLowerCase();const rows=logs.filter(l=>(!t||l.entity_type===t)).filter(l=>{const s=summary(l);return!q||[l.actor_name,s.title,s.sub].join(' ').toLowerCase().includes(q)});if(!rows.length){content.innerHTML='<div class="loadingCard">Noch keine passenden History-Einträge.</div>';return}content.innerHTML=rows.map(l=>{const s=summary(l);return`<article class="historyEntry"><div class="historyEntryHead"><div><b>${esc(s.title)}</b><div class="historyBadge">${esc(actionLabel(l))}</div></div><span>${esc(fmt(l.created_at))}</span></div><div class="historyText">${esc(s.sub)}</div><div class="historyDiff">Ausgeführt von ${esc(l.actor_name||'System')}</div></article>`}).join('')}
async function loadGroup(id){current=groups.find(g=>g.id===id)||groups[0];if(!current)return;localStorage.setItem('seasoncrew-group',current.id);const [{data:ls,error},{data:ts},{data:overrides}]=await Promise.all([sb.from('sc_history').select('*').eq('group_id',current.id).order('created_at',{ascending:false}).limit(1000),sb.from('sc_tickets').select('id,label,block,row_label,seat').eq('group_id',current.id),sb.from('match_overrides').select('id,opponent,start_date,end_date,kickoff_time,home,possible,active').eq('season',current.season)]);if(error){content.innerHTML='<div class="loadingCard">History konnte nicht geladen werden.</div>';return}tickets=new Map((ts||[]).map(t=>[t.id,t]));fixtures=new Map(BASE_M.map(m=>[m.id,{...m}]));for(const x of overrides||[]){const m=fixtures.get(x.id);if(m)fixtures.set(x.id,{...m,o:x.opponent||m.o,s:x.start_date||m.s,e:x.end_date||x.start_date||m.e,t:x.kickoff_time?String(x.kickoff_time).slice(0,5):m.t,h:x.home??m.h,pos:x.possible??m.pos})}logs=ls||[];render()}
sel.addEventListener('change',()=>loadGroup(sel.value));type.addEventListener('change',render);search.addEventListener('input',render);
async function boot(){const {data:{session}}=await sb.auth.getSession();if(!session){location.replace('index.html');return}user=session.user;const {data:p}=await sb.from('sc_profiles').select('is_superadmin').eq('id',user.id).maybeSingle();profile=p||{is_superadmin:false};let gs=[];if(profile.is_superadmin){const {data}=await sb.from('sc_groups').select('*').order('created_at');gs=data||[]}else{const {data:ms}=await sb.from('sc_group_members').select('group_id').eq('user_id',user.id);const ids=(ms||[]).map(m=>m.group_id);if(ids.length){const {data}=await sb.from('sc_groups').select('*').in('id',ids).order('created_at');gs=data||[]}}groups=gs;if(!groups.length){content.innerHTML='<div class="loadingCard">Du bist noch in keiner Crew.</div>';return}sel.innerHTML=groups.map(g=>`<option value="${g.id}">${esc(g.name)}</option>`).join('');const saved=localStorage.getItem('seasoncrew-group');sel.value=groups.some(g=>g.id===saved)?saved:groups[0].id;await loadGroup(sel.value)}boot();
