const sb=window.SeasonCrewCore?.client?.();
if(!sb)throw new Error('SeasonCrew Supabase core unavailable');
const $=id=>document.getElementById(id);
const RULE_FIELDS=[['dfb.r1','DFB · 1. Runde'],['dfb.r2','DFB · 2. Runde'],['dfb.r16','DFB · Achtelfinale'],['dfb.qf','DFB · Viertelfinale'],['dfb.sf','DFB · Halbfinale'],['dfb.final','DFB · Finale'],['cl.league','CL · Ligaphase'],['cl.playoff','CL · Play-offs'],['cl.r16','CL · Achtelfinale'],['cl.qf','CL · Viertelfinale'],['cl.sf','CL · Halbfinale'],['cl.final','CL · Finale']];
let session=null,user=null,profile=null,groups=[],currentGroup=null,members=[],tickets=[],fixtures=[],pendingRequests=[],activeInvite=null;

function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function roleLabel(v){return v==='superadmin'?'Superadmin':v==='owner'?'Owner':v==='admin'?'Admin':'Mitglied'}
function currentRole(){if(profile?.is_superadmin)return'superadmin';return members.find(m=>m.user_id===user?.id)?.role||'guest'}
function isManager(){return ['superadmin','owner','admin'].includes(currentRole())}
function canOwner(){return ['superadmin','owner'].includes(currentRole())}
function parseMoney(v){const raw=String(v??'').trim();if(!raw)return null;const n=Number(raw.replace(/\s/g,'').replace(',','.'));return Number.isFinite(n)&&n>=0?Math.round(n*100)/100:null}
function formatMoney(v){return Number(v??0).toFixed(2).replace('.',',')}
function cleanPaypal(v){return String(v||'').trim().replace(/^https?:\/\/(www\.)?paypal\.me\//i,'').replace(/^paypal\.me\//i,'').replace(/^@/,'').replace(/\/$/,'')}
function validUsername(v){return /^[A-Za-z0-9._-]{3,24}$/.test(String(v||''))}
function setStatus(id,text='',ok=false){const el=$(id);if(!el)return;el.textContent=text;el.classList.toggle('ok',!!ok)}
function toast(text){const el=$('toast');if(!el)return;el.textContent=text;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),2600)}
function getPath(obj,path){return path.split('.').reduce((a,k)=>a&&a[k]!==undefined?a[k]:undefined,obj)}
function setPath(obj,path,value){const parts=path.split('.');let cur=obj;parts.slice(0,-1).forEach(k=>{if(!cur[k]||typeof cur[k]!=='object'||Array.isArray(cur[k]))cur[k]={};cur=cur[k]});if(value==null)delete cur[parts.at(-1)];else cur[parts.at(-1)]=value}
function cloneRules(v){try{return structuredClone(v||{})}catch{return JSON.parse(JSON.stringify(v||{}))}}
function competitionMeta(key){return key==='league'?{key:'league',name:'Liga'}:key==='cup'?{key:'cup',name:'Pokal'}:key==='intl'?{key:'intl',name:'International'}:{key:'other',name:'Sonstiges'}}
function inviteLink(token){const url=new URL('index.html',location.href);url.searchParams.set('invite',token);return url.href}

async function loadGroups(){
  const {data:{session:s}}=await sb.auth.getSession();session=s;if(!session){location.replace('index.html');return false}user=session.user;
  const {data:p,error:pe}=await sb.from('sc_profiles').select('id,username,is_superadmin').eq('id',user.id).maybeSingle();if(pe)throw pe;profile=p||{username:'Mitglied',is_superadmin:false};
  if(profile.is_superadmin){const {data,error}=await sb.from('sc_groups').select('id,name,club_key,club_name,season,paypal_me,default_price,price_rules,created_by').order('created_at');if(error)throw error;groups=data||[]}
  else{const {data:ms,error:me}=await sb.from('sc_group_members').select('group_id').eq('user_id',user.id);if(me)throw me;const ids=(ms||[]).map(x=>x.group_id);if(ids.length){const {data,error}=await sb.from('sc_groups').select('id,name,club_key,club_name,season,paypal_me,default_price,price_rules,created_by').in('id',ids).order('created_at');if(error)throw error;groups=data||[]}}
  if(!groups.length){$('settingsPageSub').textContent='Du bist aktuell in keiner Crew.';$('groupSelect').innerHTML='';return false}
  $('groupSelect').innerHTML=groups.map(g=>`<option value="${g.id}">${esc(g.name)}</option>`).join('');
  const saved=localStorage.getItem('seasoncrew-group');$('groupSelect').value=groups.some(g=>g.id===saved)?saved:groups[0].id;return true;
}

async function loadGroup(id){
  const group=groups.find(g=>g.id===id)||groups[0];if(!group)return;currentGroup=group;localStorage.setItem('seasoncrew-group',group.id);
  const [{data:ms,error:me},{data:ts,error:te},{data:fs,error:fe}]=await Promise.all([
    sb.from('sc_group_members').select('group_id,user_id,role,joined_at').eq('group_id',group.id).order('joined_at'),
    sb.from('sc_tickets').select('id,label,block,row_label,seat,sort_order,active').eq('group_id',group.id).eq('active',true).order('sort_order').order('created_at'),
    sb.from('sc_fixtures').select('fixture_id,competition_key,competition_name,label,date_start,date_end,time_text,opponent,venue,price_override,active,source').eq('group_id',group.id).eq('active',true).order('date_start')
  ]);if(me||te||fe)throw(me||te||fe);members=ms||[];tickets=ts||[];fixtures=fs||[];
  const ids=members.map(m=>m.user_id);if(ids.length){const {data:ps}=await sb.from('sc_profiles').select('id,username').in('id',ids);const map=new Map((ps||[]).map(x=>[x.id,x.username]));members=members.map(m=>({...m,username:map.get(m.user_id)||'Mitglied'}))}
  pendingRequests=[];activeInvite=null;
  if(isManager()){
    const [{data:rs,error:re},{data:inv,error:ie}]=await Promise.all([
      sb.rpc('sc_admin_join_requests',{p_group:group.id}),
      sb.from('sc_invites').select('id,group_id,token,created_by,expires_at,revoked_at,created_at').eq('group_id',group.id).is('revoked_at',null).gt('expires_at',new Date().toISOString()).order('created_at',{ascending:false}).limit(1).maybeSingle()
    ]);if(re)console.warn(re);if(ie)console.warn(ie);pendingRequests=rs||[];activeInvite=inv||null;
  }
  renderAll();
}

function syncAccess(){
  document.querySelectorAll('.managerOnly').forEach(el=>el.classList.toggle('pageRoleHidden',!isManager()));
  document.querySelectorAll('.ownerOnly').forEach(el=>el.classList.toggle('pageRoleHidden',!canOwner()));
  $('leaveCrewBox').classList.toggle('pageRoleHidden',currentRole()==='owner');
}
function renderAll(){
  $('settingsPageTitle').textContent=currentGroup.name;$('settingsPageSub').textContent=`${currentGroup.club_name||'Verein'} · Saison ${String(currentGroup.season||'').replace('-',' / ')}`;$('memberRole').textContent=roleLabel(currentRole());
  $('profileUsername').value=profile.username||'';$('profileEmail').value=user.email||'';
  $('settingsGroupName').value=currentGroup.name||'';$('settingsClubName').value=currentGroup.club_name||'';$('settingsSeason').value=currentGroup.season||'';$('settingsSeason').disabled=true;$('settingsPaypal').value=cleanPaypal(currentGroup.paypal_me);$('settingsPrice').value=formatMoney(currentGroup.default_price||0);$('priceBl').value=formatMoney(currentGroup.default_price||0);
  syncAccess();renderFixtures();renderPrices();renderTickets();renderMembers();renderInvites();
  requestAnimationFrame(()=>scrollHash(false));
}

function renderFixtures(){
  const list=$('fixtureList');if(!list)return;
  list.innerHTML=fixtures.length?fixtures.map(f=>`<div class="settingsRow"><div class="settingsRowMain"><b>${esc(f.label)} · ${esc(f.opponent)}</b><small>${esc(f.competition_name||competitionMeta(f.competition_key).name)} · ${esc(f.date_start||'Termin offen')}${f.time_text?` · ${esc(String(f.time_text).slice(0,5))} Uhr`:''}${f.venue?` · ${esc(f.venue)}`:''}</small></div><div class="settingsRowActions"><div class="fixturePriceEdit"><input inputmode="decimal" value="${f.price_override==null?'':formatMoney(f.price_override)}" placeholder="Standard" data-fixture-price="${esc(f.fixture_id)}"><button class="miniButton" type="button" data-save-fixture-price="${esc(f.fixture_id)}">Preis</button></div><button class="dangerMini" type="button" data-delete-fixture="${esc(f.fixture_id)}">Löschen</button></div></div>`).join(''):'<div class="loadingCard">Noch keine eigenen Heimspiele angelegt.</div>';
  list.querySelectorAll('[data-save-fixture-price]').forEach(b=>b.addEventListener('click',()=>saveFixturePrice(b.dataset.saveFixturePrice)));
  list.querySelectorAll('[data-delete-fixture]').forEach(b=>b.addEventListener('click',()=>deleteFixture(b.dataset.deleteFixture)));
}
function renderPrices(){
  const generic=currentGroup.club_key!=='fcbayern';$('roundPriceCard').classList.toggle('hidden',generic);const grid=$('roundPriceGrid');if(generic){grid.innerHTML='';return}
  grid.innerHTML=RULE_FIELDS.map(([path,label])=>`<label>${esc(label)}<input inputmode="decimal" data-price-path="${path}" value="${typeof getPath(currentGroup.price_rules||{},path)==='number'?formatMoney(getPath(currentGroup.price_rules||{},path)):''}" placeholder="Standard"></label>`).join('');
}
function renderTickets(){
  $('ticketList').innerHTML=tickets.length?tickets.map(t=>`<div class="settingsRow"><div class="settingsRowMain"><b>${esc(t.label||[t.block,t.row_label,t.seat].filter(Boolean).join('/'))}</b><small>${[t.block&&`Block ${esc(t.block)}`,t.row_label&&`Reihe ${esc(t.row_label)}`,t.seat&&`Sitz ${esc(t.seat)}`].filter(Boolean).join(' · ')}</small></div><div class="settingsRowActions"><button class="dangerMini" type="button" data-delete-ticket="${t.id}">Löschen</button></div></div>`).join(''):'<div class="loadingCard">Noch keine Dauerkarten angelegt.</div>';
  document.querySelectorAll('[data-delete-ticket]').forEach(b=>b.addEventListener('click',()=>deleteTicket(b.dataset.deleteTicket)));
}
function renderMembers(){
  const me=currentRole(),canGrant=canOwner();
  $('memberList').innerHTML=members.map(m=>{const self=m.user_id===user.id,owner=m.role==='owner',removeAllowed=!owner&&!self&&isManager()&&(canGrant||m.role==='guest');return `<div class="settingsRow"><div class="settingsRowMain"><b>@${esc(m.username)}</b><small>Seit ${new Intl.DateTimeFormat('de-DE').format(new Date(m.joined_at))}</small></div><div class="settingsRowActions">${canGrant&&!owner?`<select class="memberRoleSelect" data-member-role="${m.user_id}"><option value="guest" ${m.role==='guest'?'selected':''}>Mitglied</option><option value="admin" ${m.role==='admin'?'selected':''}>Admin</option></select><button class="miniButton" type="button" data-save-role="${m.user_id}">Rolle speichern</button><button class="miniButton" type="button" data-transfer-owner="${m.user_id}">Owner übertragen</button>`:`<span class="roleBadgeSettings ${m.role}">${roleLabel(m.role)}</span>`}${removeAllowed?`<button class="dangerMini" type="button" data-remove-member="${m.user_id}">Entfernen</button>`:''}</div></div>`}).join('');
  document.querySelectorAll('[data-save-role]').forEach(b=>b.addEventListener('click',()=>saveMemberRole(b.dataset.saveRole)));
  document.querySelectorAll('[data-transfer-owner]').forEach(b=>b.addEventListener('click',()=>transferOwner(b.dataset.transferOwner)));
  document.querySelectorAll('[data-remove-member]').forEach(b=>b.addEventListener('click',()=>removeMember(b.dataset.removeMember)));
}
async function renderInvites(){
  const box=$('inviteBox');if(!isManager()){box.textContent='';return}
  if(!activeInvite){box.innerHTML='Noch keine aktive Einladung. Erstelle einen neuen Link.'}
  else{const link=inviteLink(activeInvite.token),expires=new Intl.DateTimeFormat('de-DE',{dateStyle:'medium',timeStyle:'short'}).format(new Date(activeInvite.expires_at));box.innerHTML=`<b>Aktive Einladung</b><div class="inviteCode"><code>${esc(activeInvite.token)}</code><button class="miniButton" type="button" id="copyInviteCode">Code kopieren</button></div><div class="inviteLink">${esc(link)}</div><div class="settingsActions"><button class="miniButton" type="button" id="copyInviteLink">Link kopieren</button><button class="miniButton" type="button" id="shareInviteLink">Teilen</button></div><small style="display:block;margin-top:8px;color:#858995">Gültig bis ${esc(expires)}</small>`;$('copyInviteCode')?.addEventListener('click',async()=>{await navigator.clipboard.writeText(activeInvite.token);toast('Code kopiert')});$('copyInviteLink')?.addEventListener('click',async()=>{await navigator.clipboard.writeText(link);toast('Link kopiert')});$('shareInviteLink')?.addEventListener('click',async()=>{try{if(navigator.share)await navigator.share({title:`Einladung zu ${currentGroup.name}`,text:`SeasonCrew Einladungscode: ${activeInvite.token}`,url:link});else await navigator.clipboard.writeText(link)}catch(e){if(e?.name!=='AbortError')toast('Teilen nicht möglich')}})}
  const canGrant=canOwner();$('joinRequestList').innerHTML=pendingRequests.length?pendingRequests.map(r=>`<div class="settingsRow"><div class="settingsRowMain"><b>@${esc(r.username||'Bewerber')}</b><small>Anfrage ${new Intl.DateTimeFormat('de-DE',{dateStyle:'short',timeStyle:'short'}).format(new Date(r.requested_at))}</small></div><div class="settingsRowActions"><button class="miniButton" type="button" data-approve-member="${r.id}" data-user="${r.user_id}">Als Mitglied</button>${canGrant?`<button class="miniButton" type="button" data-approve-admin="${r.id}" data-user="${r.user_id}">Als Admin</button>`:''}<button class="dangerMini" type="button" data-reject-request="${r.id}" data-user="${r.user_id}">Ablehnen</button></div></div>`).join(''):'<div class="loadingCard">Keine offenen Bewerbungen.</div>';
  document.querySelectorAll('[data-approve-member]').forEach(b=>b.addEventListener('click',()=>decideRequest(b.dataset.approveMember,b.dataset.user,true,'guest')));document.querySelectorAll('[data-approve-admin]').forEach(b=>b.addEventListener('click',()=>decideRequest(b.dataset.approveAdmin,b.dataset.user,true,'admin')));document.querySelectorAll('[data-reject-request]').forEach(b=>b.addEventListener('click',()=>decideRequest(b.dataset.rejectRequest,b.dataset.user,false,'guest')));
}

$('groupSelect').addEventListener('change',()=>loadGroup($('groupSelect').value));
$('saveProfileBtn').addEventListener('click',async()=>{const username=$('profileUsername').value.trim();if(!validUsername(username)){setStatus('profileStatus','Bitte 3–24 gültige Zeichen verwenden.');return}if(username.toLowerCase()!==String(profile.username||'').toLowerCase()){const {data,error}=await sb.rpc('sc_username_available',{p_username:username});if(error||!data){setStatus('profileStatus',error?.message||'Dieser Nutzername ist bereits vergeben.');return}}const {error}=await sb.from('sc_profiles').update({username,updated_at:new Date().toISOString()}).eq('id',user.id);if(error){setStatus('profileStatus',error.message);return}await sb.auth.updateUser({data:{username}});profile.username=username;setStatus('profileStatus','Profil gespeichert ✓',true);toast('Profil gespeichert')});
$('saveGroupBtn').addEventListener('click',async()=>{if(!isManager())return;const name=$('settingsGroupName').value.trim(),club=$('settingsClubName').value.trim(),price=parseMoney($('settingsPrice').value);if(!name||!club||price==null){setStatus('crewStatus','Bitte Crew-Name, Verein und gültigen Standardpreis angeben.');return}const update={name,club_name:club,paypal_me:cleanPaypal($('settingsPaypal').value)||null,default_price:price,updated_at:new Date().toISOString()};const {data,error}=await sb.from('sc_groups').update(update).eq('id',currentGroup.id).select('id,name,club_key,club_name,season,paypal_me,default_price,price_rules,created_by').single();if(error){setStatus('crewStatus',error.message);return}currentGroup=data;groups=groups.map(g=>g.id===data.id?data:g);$('groupSelect').selectedOptions[0].textContent=data.name;$('priceBl').value=formatMoney(data.default_price);setStatus('crewStatus','Crew gespeichert ✓',true);renderAll();toast('Crew gespeichert')});
$('addFixtureBtn').addEventListener('click',async()=>{if(!isManager())return;const label=$('fixtureLabel').value.trim(),opponent=$('fixtureOpponent').value.trim(),venue=$('fixtureVenue').value.trim(),date=$('fixtureDate').value,time=$('fixtureTime').value,price=parseMoney($('fixturePrice').value),meta=competitionMeta($('fixtureCompetition').value);if(!label||!opponent||!date){setStatus('fixtureStatus','Bitte Bezeichnung, Gegner und Datum angeben.');return}const {data,error}=await sb.from('sc_fixtures').insert({group_id:currentGroup.id,competition_key:meta.key,competition_name:meta.name,label,date_start:date,date_end:date,time_text:time||null,opponent,venue:venue||null,is_home:true,price_override:price,source:'manual',created_by:user.id}).select('fixture_id,competition_key,competition_name,label,date_start,date_end,time_text,opponent,venue,price_override,active,source').single();if(error){setStatus('fixtureStatus',error.message);return}fixtures.push(data);['fixtureLabel','fixtureOpponent','fixtureVenue','fixtureDate','fixtureTime','fixturePrice'].forEach(id=>$(id).value='');renderFixtures();setStatus('fixtureStatus','Heimspiel hinzugefügt ✓',true);toast('Heimspiel hinzugefügt')});
async function saveFixturePrice(id){const input=document.querySelector(`[data-fixture-price="${CSS.escape(id)}"]`),raw=input?.value.trim()||'',price=raw?parseMoney(raw):null;if(raw&&price==null){setStatus('fixtureStatus','Ungültiger Spielpreis.');return}const {data,error}=await sb.from('sc_fixtures').update({price_override:price,updated_at:new Date().toISOString()}).eq('group_id',currentGroup.id).eq('fixture_id',id).select('fixture_id,price_override').single();if(error){setStatus('fixtureStatus',error.message);return}const f=fixtures.find(x=>x.fixture_id===id);if(f)f.price_override=data.price_override;setStatus('fixtureStatus','Spielpreis gespeichert ✓',true);toast('Spielpreis gespeichert')}
async function deleteFixture(id){if(!confirm('Dieses Heimspiel wirklich löschen?'))return;const {error}=await sb.from('sc_fixtures').delete().eq('group_id',currentGroup.id).eq('fixture_id',id);if(error){setStatus('fixtureStatus',error.message);return}fixtures=fixtures.filter(f=>f.fixture_id!==id);renderFixtures();toast('Heimspiel gelöscht')}
$('savePricesBtn').addEventListener('click',async()=>{if(!isManager())return;const base=parseMoney($('priceBl').value);if(base==null){setStatus('priceStatus','Bitte gültigen Standardpreis eingeben.');return}const rules=cloneRules(currentGroup.price_rules);if(currentGroup.club_key==='fcbayern'){let invalid=false;document.querySelectorAll('[data-price-path]').forEach(input=>{const raw=input.value.trim(),v=raw?parseMoney(raw):null;if(raw&&v==null)invalid=true;else setPath(rules,input.dataset.pricePath,v)});if(invalid){setStatus('priceStatus','Mindestens ein Rundenpreis ist ungültig.');return}}const {data,error}=await sb.from('sc_groups').update({default_price:base,price_rules:rules,updated_at:new Date().toISOString()}).eq('id',currentGroup.id).select('id,name,club_key,club_name,season,paypal_me,default_price,price_rules,created_by').single();if(error){setStatus('priceStatus',error.message);return}currentGroup=data;groups=groups.map(g=>g.id===data.id?data:g);$('settingsPrice').value=formatMoney(base);setStatus('priceStatus','Preise gespeichert ✓',true);toast('Preise gespeichert')});
$('createInviteBtn').addEventListener('click',async()=>{if(!isManager())return;setStatus('inviteStatus','Einladung wird erstellt …');const {data,error}=await sb.rpc('sc_create_invite',{p_group:currentGroup.id,p_days:14});if(error){setStatus('inviteStatus',error.message);return}activeInvite=data?.[0]||null;await renderInvites();setStatus('inviteStatus','Neue Einladung erstellt ✓',true);toast('Einladung erstellt')});
async function decideRequest(id,uid,approve,role){if(!isManager())return;const {error}=await sb.rpc('sc_decide_join_request_v2',{p_request:id,p_group:currentGroup.id,p_user:uid,p_approve:approve,p_role:role});if(error){setStatus('inviteStatus',error.message);return}await loadGroup(currentGroup.id);toast(approve?'Bewerbung freigegeben':'Bewerbung abgelehnt')}
$('addTicketBtn').addEventListener('click',async()=>{if(!isManager())return;const block=$('ticketBlock').value.trim(),row=$('ticketRow').value.trim(),seat=$('ticketSeat').value.trim();if(!block&&!row&&!seat){setStatus('ticketStatus','Bitte Block, Reihe oder Sitz angeben.');return}const label=[block,row,seat].filter(Boolean).join('/');const {data,error}=await sb.from('sc_tickets').insert({group_id:currentGroup.id,label,block:block||null,row_label:row||null,seat:seat||null,sort_order:tickets.length+1}).select().single();if(error){setStatus('ticketStatus',error.message);return}tickets.push(data);$('ticketBlock').value=$('ticketRow').value=$('ticketSeat').value='';renderTickets();setStatus('ticketStatus','Dauerkarte hinzugefügt ✓',true);toast('Dauerkarte hinzugefügt')});
async function deleteTicket(id){if(!confirm('Dauerkarte wirklich löschen? Vorhandene Belegungen dieser Karte werden ebenfalls entfernt.'))return;const {error}=await sb.from('sc_tickets').delete().eq('id',id).eq('group_id',currentGroup.id);if(error){setStatus('ticketStatus',error.message);return}tickets=tickets.filter(t=>t.id!==id);renderTickets();toast('Dauerkarte gelöscht')}
async function saveMemberRole(uid){if(!canOwner())return;const select=document.querySelector(`[data-member-role="${uid}"]`),role=select?.value;if(!role)return;const {error}=await sb.rpc('sc_manage_member_role',{p_group:currentGroup.id,p_user:uid,p_role:role});if(error){setStatus('memberStatus',error.message);return}await loadGroup(currentGroup.id);toast('Rolle gespeichert')}
async function transferOwner(uid){if(!canOwner()||!confirm('Owner-Rolle wirklich auf dieses Mitglied übertragen?'))return;const {error}=await sb.rpc('sc_transfer_group_owner',{p_group:currentGroup.id,p_new_owner:uid});if(error){setStatus('memberStatus',error.message);return}await loadGroup(currentGroup.id);toast('Owner übertragen')}
async function removeMember(uid){if(!isManager()||!confirm('Mitglied wirklich aus der Crew entfernen?'))return;const {error}=await sb.rpc('sc_remove_group_member',{p_group:currentGroup.id,p_user:uid});if(error){setStatus('memberStatus',error.message);return}await loadGroup(currentGroup.id);toast('Mitglied entfernt')}
$('leaveCrewBtn').addEventListener('click',async()=>{if(currentRole()==='owner'){setStatus('securityStatus','Übertrage zuerst die Owner-Rolle.');return}if(!confirm('Crew wirklich verlassen?'))return;const {error}=await sb.rpc('sc_leave_group',{p_group:currentGroup.id});if(error){setStatus('securityStatus',error.message);return}localStorage.removeItem('seasoncrew-group');location.replace('index.html')});
$('rolloverBtn').addEventListener('click',async()=>{if(!canOwner())return;const season=$('newSeasonValue').value.trim();if(!/^\d{4}-\d{2}$/.test(season)){setStatus('securityStatus','Bitte Saison als 2027-28 eingeben.');return}if(!confirm(`Neue Saison ${season.replace('-','/')} starten?`))return;const {error}=await sb.rpc('sc_rollover_season',{p_group:currentGroup.id,p_new_season:season});if(error){setStatus('securityStatus',error.message);return}currentGroup.season=season;$('settingsSeason').value=season;$('settingsPageSub').textContent=`${currentGroup.club_name} · Saison ${season.replace('-',' / ')}`;toast('Neue Saison gestartet')});
$('deleteCrewBtn').addEventListener('click',async()=>{if(!canOwner())return;const typed=prompt(`Zum Löschen bitte den Crew-Namen exakt eingeben:\n${currentGroup.name}`);if(typed!==currentGroup.name)return;const {data,error}=await sb.from('sc_groups').delete().eq('id',currentGroup.id).select('id').maybeSingle();if(error||!data){setStatus('securityStatus',error?.message||'Crew konnte nicht gelöscht werden.');return}localStorage.removeItem('seasoncrew-group');location.replace('index.html')});

function scrollHash(smooth=true){const id=(location.hash||'#profile').slice(1),target=document.getElementById(id);if(target&&!target.classList.contains('pageRoleHidden'))target.scrollIntoView({behavior:smooth?'smooth':'auto',block:'start'})}
$('settingsNav').addEventListener('click',e=>{const a=e.target.closest('a[data-nav]');if(!a)return;document.querySelectorAll('#settingsNav a').forEach(x=>x.classList.toggle('active',x===a))});
window.addEventListener('hashchange',()=>scrollHash(true));
const io=new IntersectionObserver(entries=>{const visible=entries.filter(e=>e.isIntersecting).sort((a,b)=>b.intersectionRatio-a.intersectionRatio)[0];if(!visible)return;document.querySelectorAll('#settingsNav a').forEach(a=>a.classList.toggle('active',a.dataset.nav===visible.target.id))},{rootMargin:'-120px 0px -65% 0px',threshold:[0,.1,.4]});
document.querySelectorAll('.settingsSection').forEach(s=>io.observe(s));

async function boot(){try{if(!await loadGroups())return;await loadGroup($('groupSelect').value)}catch(error){console.error(error);$('settingsPageSub').textContent='Einstellungen konnten nicht geladen werden.';toast('Einstellungen konnten nicht geladen werden')}}
boot();
