import { createClient } from "https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.111.0/+esm";
const sb=createClient("https://kmhadzujovvxvpgblgkk.supabase.co","sb_publishable_JDcJGMDybnrOZcSRqtpzDg_6Ul0jr2Y",{auth:{persistSession:true,autoRefreshToken:true}});
const STATE_SEASON="2026-27-tom",FIXTURE_SEASON="2026-27",VARIANT="tom",PERSON={t1:"Tom1",t2:"Tom2",s1:"Staudter 1",s2:"Staudter 2"};
const content=document.getElementById("content"),userFilter=document.getElementById("userFilter"),typeFilter=document.getElementById("typeFilter"),search=document.getElementById("search");let LOGS=[],MATCHES=new Map();
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function same(a,b){return JSON.stringify(a??null)===JSON.stringify(b??null)}
function fmtDate(ts){return new Intl.DateTimeFormat("de-DE",{dateStyle:"medium",timeStyle:"short",timeZone:"Europe/Berlin"}).format(new Date(ts))}
function euro(v){const n=Number(v);return Number.isFinite(n)?new Intl.NumberFormat("de-DE",{style:"currency",currency:"EUR"}).format(n):"–"}
function gameName(id){const m=MATCHES.get(id);if(!m)return id||"Saisonübersicht";const comp=id.startsWith("bl")?"Bundesliga":id.startsWith("dfb")?"DFB-Pokal":"Champions League";return `${comp} · ${m.opponent||"Gegner offen"}`}
function names(arr,n={}){return(arr||[]).map(v=>{const base=PERSON[v]||v,name=String(n[v]||"").trim();return name?`${base} (${name})`:base}).join(", ")||"Offen"}
function relevant(log){if(log.entity_type==="season_state")return log.entity_id===STATE_SEASON;if(log.entity_type==="paypal")return log.after_data?.variant===VARIANT;if(log.entity_type==="login")return log.after_data?.variant===VARIANT||log.entity_id==="tom-session";return log.entity_type==="fixture"||log.entity_type==="sync_run"}
function stateChanges(log){
  const a=log.before_data||{},b=log.after_data||{},out=[],ids=new Set([
    ...Object.keys(a.assignments||{}),...Object.keys(b.assignments||{}),
    ...Object.keys(a.names||{}),...Object.keys(b.names||{}),
    ...Object.keys(a.paid||{}),...Object.keys(b.paid||{}),
    ...Object.keys(a.notes||{}),...Object.keys(b.notes||{}),
    ...Object.keys(a.prices||{}),...Object.keys(b.prices||{})
  ]);
  for(const id of ids){
    const aa=(a.assignments||{})[id]||[],ba=(b.assignments||{})[id]||[],an=(a.names||{})[id]||{},bn=(b.names||{})[id]||{};
    if(!same(aa,ba))out.push({id,text:`Belegung: ${names(aa,an)} → ${names(ba,bn)}`});
    for(const p of Object.keys(PERSON))if((an[p]||"")!==(bn[p]||""))out.push({id,text:`${PERSON[p]} · Name: "${an[p]||"–"}" → "${bn[p]||"–"}"`});
    const ap=(a.paid||{})[id]||{},bp=(b.paid||{})[id]||{};
    for(const p of Object.keys(PERSON))if(!!ap[p]!==!!bp[p])out.push({id,text:`${PERSON[p]}: ${bp[p]?"bezahlt":"nicht bezahlt"}`});
    if(((a.notes||{})[id]||"")!==((b.notes||{})[id]||""))out.push({id,text:"Notiz geändert"});
    const op=(a.prices||{})[id],np=(b.prices||{})[id];if(!same(op,np))out.push({id,text:`Ticketpreis: ${op==null?"–":euro(op)} → ${np==null?"–":euro(np)}`});
  }
  return out.length?out:[{id:null,text:"Saisonübersicht geändert"}];
}
function fixtureChanges(log){const a=log.before_data||{},b=log.after_data||{},out=[],fields=[["opponent","Gegner"],["start_date","Datum"],["end_date","Datumsende"],["kickoff_time","Anstoß"],["home","Heim/Auswärts"],["active","Aktiv"]];for(const[k,label]of fields)if(!same(a[k],b[k]))out.push({id:log.entity_id,text:`${label}: ${a[k]??"–"} → ${b[k]??"–"}`});return out.length?out:[{id:log.entity_id,text:"Offizielle Termindaten aktualisiert"}]}
function syncFixtureLogs(syncLog){const st=Date.parse(syncLog.created_at);if(!Number.isFinite(st))return[];const syncs=LOGS.filter(x=>x.entity_type==="sync_run");return LOGS.filter(f=>{if(f.entity_type!=="fixture")return false;const ft=Date.parse(f.created_at);if(!Number.isFinite(ft)||ft>st||st-ft>60000)return false;const owner=syncs.filter(s=>{const t=Date.parse(s.created_at);return Number.isFinite(t)&&t>=ft&&t-ft<=60000}).sort((a,b)=>Date.parse(a.created_at)-Date.parse(b.created_at))[0];return owner?.id===syncLog.id}).sort((a,b)=>Date.parse(a.created_at)-Date.parse(b.created_at))}
function syncChanges(log){const b=log.after_data||{},status=b.status==="success"?"erfolgreich":b.status==="failed"?"fehlgeschlagen":(b.status||"ausgeführt"),out=[{id:null,text:`Spieltagssync ${status}`}],fixtures=syncFixtureLogs(log);if(Number.isFinite(Number(b.found_count)))out.push({id:null,text:`Gefundene Spiele: ${b.found_count}`});if(fixtures.length){out.push({id:null,text:`Tatsächlich geänderte Einträge: ${fixtures.length}`});fixtures.forEach(f=>out.push({id:f.entity_id,text:`Aktualisiert: ${gameName(f.entity_id)}`}))}else if(b.status==="success")out.push({id:null,text:"Keine Termindaten geändert"});if(b.message)out.push({id:null,text:String(b.message)});return out}
function paypalChanges(log){const b=log.after_data||{},action=b.action==="link_copied"?"PayPal-Link kopiert":b.action==="share_opened"?"Zahlungsaufforderung geteilt":b.action==="message_copied"?"Zahlungsaufforderung kopiert":"PayPal-Zahlungsaufforderung",out=[{id:log.entity_id,text:action}];if(b.person)out.push({id:log.entity_id,text:`Empfänger: ${b.person}`});if(b.ticket)out.push({id:log.entity_id,text:`Jahreskarte: ${b.ticket}`});if(b.opponent)out.push({id:log.entity_id,text:`Gegner: ${b.opponent}`});if(b.amount!=null)out.push({id:log.entity_id,text:`Betrag: ${euro(b.amount)}`});return out}
function changesFor(log){if(log.entity_type==="login")return[{id:null,text:"Eingeloggt"}];if(log.entity_type==="paypal")return paypalChanges(log);if(log.entity_type==="fixture")return fixtureChanges(log);if(log.entity_type==="sync_run")return syncChanges(log);return stateChanges(log)}
function typeLabel(log){if(log.entity_type==="login")return"Login";if(log.entity_type==="paypal")return"PayPal";if(log.entity_type==="fixture")return"Termin-Sync";if(log.entity_type==="sync_run")return"Spieltagssync";return"Änderung"}
function render(){const uf=userFilter.value,tf=typeFilter.value,q=search.value.trim().toLowerCase(),rows=LOGS.filter(log=>{if(uf&&log.actor_name!==uf)return false;if(tf&&log.entity_type!==tf)return false;const changes=changesFor(log),hay=[log.actor_name,gameName(log.entity_id),...changes.map(x=>x.text)].join(" ").toLowerCase();return!q||hay.includes(q)});if(!rows.length){content.className="empty";content.textContent="Noch keine History-Einträge vorhanden.";return}content.className="log";content.innerHTML=rows.map(log=>{const changes=changesFor(log),ids=[...new Set(changes.map(x=>x.id).filter(Boolean))],syncFixtures=log.entity_type==="sync_run"?syncFixtureLogs(log):[],games=log.entity_type==="login"?"Anmeldung":log.entity_type==="sync_run"?(syncFixtures.length?syncFixtures.map(f=>gameName(f.entity_id)).join(" · "):"Spieltagssynchronisierung"):(ids.length?ids.map(gameName).join(" · "):gameName(log.entity_id)),system=log.actor_name==="System",who=log.entity_type==="login"?`${esc(log.actor_name||"Benutzer")} hat sich eingeloggt`:`Ausgeführt von ${esc(log.actor_name||"Benutzer")}`;return`<article class="entry"><div class="row"><div><div class="who">${who}</div><div class="time">${fmtDate(log.created_at)}</div></div><span class="badge ${system?"system":""}">${typeLabel(log)}</span></div><div class="game">${esc(games)}</div><ul class="changes">${changes.map(c=>`<li>${esc(c.text)}</li>`).join("")}</ul></article>`}).join("")}
async function boot(){const {data:{session}}=await sb.auth.getSession();if(!session){location.replace("index.html");return}const [{data:logs,error},{data:matches}]=await Promise.all([sb.from("history_log").select("id,created_at,actor_name,entity_type,entity_id,before_data,after_data").order("created_at",{ascending:false}).limit(1000),sb.from("match_overrides").select("id,opponent").eq("season",FIXTURE_SEASON)]);if(error){content.className="empty";content.textContent="History konnte nicht geladen werden.";return}MATCHES=new Map((matches||[]).map(x=>[x.id,x]));LOGS=(logs||[]).filter(relevant);[...new Set(LOGS.map(x=>x.actor_name).filter(Boolean))].sort().forEach(n=>userFilter.insertAdjacentHTML("beforeend",`<option value="${esc(n)}">${esc(n)}</option>`));userFilter.onchange=typeFilter.onchange=search.oninput=render;render()}
boot();